# NOTE: names in parentheses are special, all other names are not!
(project):
    
    # a central place for filepaths
    (path_to):
        this_file: "./info.yaml"
        face_html: desktop/index.html
        capturer_mmap: robot/capturer_mmap
        file_server_public_key: desktop/cert.pem
        file_server_private_key: desktop/key.pem
        py_gpio_link: robot/py_gpio_link.py
    
    (local_data): ./local_data.ignore.yaml
    
    (profiles):
        (default):
            image_height: 480
            image_width:  640
            phone:
                fov: 76 # degrees
            desktop:
                ip_address: 192.168.43.229 # UNIQUE_ID_fo4i3jf84309583
                file_server_port: 7071
                web_socket_port:  9093